#build.yml
- name: Ansible playbook for building the class VM
  
  hosts: localhost
  
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ansible_playbook_python}}"
  
  tasks:
  
  - name: Add Powershell APT repo
    apt:
      deb: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
      
  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest

  - name: "apt-get update"
    apt:
      update_cache: yes
    
  - name: Install packages (apt)
    ansible.builtin.package:
      name:
        - nmap
        - ncat
        - net-tools
        - tcpdump
        - curl
        - wireshark
        - tshark
        - libpam-google-authenticator
        - qrencode
        - keepassxc
        - hping3
        - vim
        - wget
        - powershell
        - apt-transport-https
        - software-properties-common
        - openssh-server
        - libaprutil1-dev
        - gcc
        - libpcre3-dev
      state: present
      
  - name: Make script executable
    file:
      path: start-nmap-exercise.sh
      mode: '0744'
  
  - name: Enable and start SSHD
    ansible.builtin.systemd:
      state: started
      enabled: yes
      name: sshd
  
  - name: download Apache 2.4.49
    get_url:
      url: https://archive.apache.org/dist/httpd/httpd-2.4.49.tar.bz2
      dest: /tmp/httpd-2.4.49.tar.bz2
      
  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/httpd-2.4.49.tar.bz2
      dest: /tmp
      remote_src: yes
  
  - name: Configuring Apache source with custom modules
    command: "./configure"
    args:
      chdir: /tmp/httpd-2.4.49
  
  - name: Building and Installing Apache
    shell: make && make install
    args:
      chdir: /tmp/httpd-2.4.49
      
  - name: Test if Wazuh appears to be already installed
    stat:
      path: /var/ossec/bin/wazuh-monitord
    register: wazuh
      
  - name: Download the Wazuh unattended install script
    get_url:
      url: https://packages.wazuh.com/resources/4.2/open-distro/unattended-installation/unattended-installation.sh
      dest: /tmp/unattended-installation.sh
    when: not wazuh.stat.exists 
    
  - name: Run the Wazuh unattended install script (reinstall)
    shell: /bin/bash /tmp/unattended-installation.sh -o > /tmp/wazuh-unattended-installation-output.log
    when: not wazuh.stat.exists
  
  - name: Install pre-reqs before running remaining.yml
    command: "ansible-galaxy collection install community.general"
  
  # this should be the last step, kludgey but works
  - name: Run remaining.yml
    command: "ansible-playbook remaining.yml"
