#build.yml
- name: Ansible playbook for building the class VM
  
  hosts: localhost
  
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ansible_playbook_python}}"
  
  tasks:
  
  - name: Add Powershell APT repo
    apt:
      deb: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
  
  - name: Add KeePassXC repo
    ansible.builtin.apt_repository:
      repo: ppa:phoerious/keepassxc
      state: present
      
  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest

  - name: "apt-get update"
    apt:
      update_cache: yes
    
  - name: Install packages (apt)
    ansible.builtin.package:
      name:
        - gedit
        - nmap
        - ncat
        - net-tools
        - tcpdump
        - curl
        - wireshark
        - tshark
        - keepassxc
        - libpam-google-authenticator
        - qrencode
        - hping3
        - hydra
        - hydra-gtk
        - vim
        - wget
        - tilix
        - powershell
        - apt-transport-https
        - software-properties-common
        - openssh-server
        - libaprutil1-dev
        - gcc
        - make
        - libpcre3-dev
        - john
      state: present
  
  - name: Make script executable
    file:
      path: "{{ item }}"
      mode: '0744'
    loop:
      - start-nmap-exercise.sh
      - stop-nmap-exercise.sh
      - start-pentest.sh
      - stop-pentest.sh
      - pentest-exercise.sh
      - testpermissions.sh
      
  - name: Update permissions for exercise
    file:
      path: /etc/shadow
      mode: '0644'
  
  - name: Enable and start SSHD
    ansible.builtin.systemd:
      state: started
      enabled: yes
      name: sshd
      
  - name: Test if vulnerable Apache already installed
    ansible.builtin.stat:
      path: /usr/local/apache2/bin/httpd
    register: httpdBin
  
  - name: download Apache 2.4.49
    get_url:
      url: https://archive.apache.org/dist/httpd/httpd-2.4.49.tar.bz2
      dest: /tmp/httpd-2.4.49.tar.bz2
    when: not httpdBin.stat.exists
      
  - name: Unarchive Apache tarball
    ansible.builtin.unarchive:
      src: /tmp/httpd-2.4.49.tar.bz2
      dest: /tmp
      remote_src: yes
    when: not httpdBin.stat.exists
  
  - name: Configuring Apache source
    command: "./configure"
    args:
      chdir: /tmp/httpd-2.4.49
    when: not httpdBin.stat.exists
  
  - name: Build and Install vulnerable Apache
    shell: make && make install
    args:
      chdir: /tmp/httpd-2.4.49
    when: not httpdBin.stat.exists
  
  - name: Add NSE
    get_url:
      url: https://raw.githubusercontent.com/RootUp/PersonalStuff/master/http-vuln-cve-2021-41773.nse
      dest: /usr/share/nmap/scripts/http-vuln-cve2021-41773.nse
      
  - name: Test if Wazuh appears to be already installed
    stat:
      path: /var/ossec/bin/wazuh-monitord
    register: wazuh
      
  - name: Download the Wazuh unattended install script
    get_url:
      url: https://packages.wazuh.com/resources/4.2/open-distro/unattended-installation/unattended-installation.sh
      dest: /tmp/unattended-installation.sh
    when: not wazuh.stat.exists 
    
  - name: Run the Wazuh unattended install script (reinstall)
    shell: /bin/bash /tmp/unattended-installation.sh -o > /tmp/wazuh-unattended-installation-output.log
    when: not wazuh.stat.exists
  
  - name: Test if ansible-galaxy collection module installed
    ansible.builtin.stat:
      path: /root/.ansible/collections/ansible_collections/community/general/plugins/modules/snap.py
    register: snap
  
  - name: Install pre-req ansible-galaxy collection before running remaining.yml
    command: "ansible-galaxy collection install community.general"
    when: not snap.stat.exists
  
  # this should be the last step, kludgey but works
  - name: Run remaining.yml
    command: "ansible-playbook remaining.yml"
