#build.yml
- name: Ansible playbook for building the class VM
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ansible_playbook_python}}"
  tasks:
  
  - name: Install packages
    ansible.builtin.package:
      name:
        - nmap
        - tcpdump
        - curl
        - wireshark
      state: present
      
  - name: Download the Wazuh unattended install script
    get_url:
      url: https://packages.wazuh.com/resources/4.2/open-distro/unattended-installation/unattended-installation.sh
      dest: /tmp/unattended-installation.sh
      
  - name: Run the Wazuh unattended install script
    command: bash /tmp/unattended-installation.sh
